#!/usr/bin/env python3
"""
GENIUS PSEUDOMONAS AERUGINOSA ULTIMATE REPORTER
================================================================================
Advanced HTML parser and gene-centric report generator for P. aeruginosa genomic data.
Processes outputs from PseudoScope pipeline (MLST, PAST serotyping, AMRfinder,
ABRicate databases, FASTA QC) and creates an interactive HTML report with:
- Gene-centric tables (genes shown with all genomes that carry them)
- Sortable, searchable tables
- ST and O-type distribution tables + ST-O combination table only
- FASTA QC metrics integration
- AI assistant guide
- Filter buttons for key AMR and virulence genes (20-25)
- CSV exports for all major tables
- No truncation of gene/genome lists
- Brown-themed design with scientific explanations per tab

Author: Brown Beckley <brownbeckley94@gmail.com>
Affiliation: University of Ghana Medical School, Department of Medical Biochemistry
Version: 1.0.0 (P. aeruginosa ultimate)
Date: 2026-04-22
License: MIT
================================================================================
"""

import os
import sys
import json
import re
import argparse
import pandas as pd
import numpy as np
from pathlib import Path
from typing import Dict, List, Set, Tuple, Any, Optional
from datetime import datetime
from collections import defaultdict, Counter
import warnings
warnings.filterwarnings('ignore')

from bs4 import BeautifulSoup

# =============================================================================
# HTML PARSER CLASS 
# =============================================================================
class PseudomonasHTMLParser:
    """
    Parses all HTML reports generated by the PseudoScope pipeline.
    """
    
    def __init__(self):
        self.abricate_databases = [
            'ncbi', 'card', 'resfinder', 'vfdb', 'argannot',
            'plasmidfinder', 'megares', 'ecoli_vf', 'bacmet2'
        ]
    
    def normalize_sample_id(self, sample_id: str) -> str:
        sample = str(sample_id)
        for ext in ['.fna', '.fasta', '.fa', '.gb', '.gbk', '.gbff', '.txt', '.tsv', '.csv']:
            if sample.endswith(ext):
                sample = sample[:-len(ext)]
        if '/' in sample or '\\' in sample:
            sample = Path(sample).name
        return sample.strip()
    
    def clean_st(self, st_str: str) -> str:
        if not st_str or st_str == 'ND':
            return 'ND'
        st_str = str(st_str).strip()
        if not st_str.upper().startswith('ST'):
            st_str = 'ST' + st_str
        return st_str
    
    def parse_html_table(self, html_content: str, table_index: int = 0) -> pd.DataFrame:
        try:
            soup = BeautifulSoup(html_content, 'html.parser')
            tables = soup.find_all('table')
            if not tables or table_index >= len(tables):
                return pd.DataFrame()
            table = tables[table_index]
            rows = table.find_all('tr')
            if not rows:
                return pd.DataFrame()
            headers = [th.get_text().strip() for th in rows[0].find_all(['th', 'td'])]
            data = []
            for row in rows[1:]:
                cols = row.find_all(['td', 'th'])
                if cols:
                    row_data = [col.get_text().strip() for col in cols]
                    if len(row_data) == len(headers):
                        data.append(row_data)
            if not data:
                return pd.DataFrame()
            return pd.DataFrame(data, columns=headers)
        except Exception as e:
            print(f"  ⚠️ Table parsing error: {e}")
            return pd.DataFrame()
    
    def parse_qc_report(self, file_path: Path) -> Dict[str, Dict]:
        print(f"  🧬 Parsing FASTA QC: {file_path.name}")
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                html = f.read()
            df = self.parse_html_table(html, 0)
            if df.empty:
                return {}
            sample_col = None
            for col in df.columns:
                if 'filename' in col.lower() or 'sample' in col.lower() or col == df.columns[0]:
                    sample_col = col
                    break
            if not sample_col:
                return {}
            results = {}
            for _, row in df.iterrows():
                sample_raw = row[sample_col]
                if not sample_raw:
                    continue
                sample = self.normalize_sample_id(sample_raw)
                qc_data = {}
                for col in df.columns:
                    if col == sample_col:
                        continue
                    val = row[col]
                    if pd.isna(val) or val == '' or val == 'ND':
                        qc_data[col] = 'ND'
                    else:
                        cleaned = str(val).replace('%', '').replace(',', '').strip()
                        try:
                            qc_data[col] = float(cleaned)
                        except:
                            qc_data[col] = str(val)
                results[sample] = qc_data
            print(f"    ✓ Parsed {len(results)} samples")
            return results
        except Exception as e:
            print(f"    ❌ Error parsing QC: {e}")
            return {}
    
    def parse_mlst_report(self, file_path: Path) -> Dict[str, Dict]:
        print(f"  🧬 Parsing MLST: {file_path.name}")
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                html_content = f.read()
            soup = BeautifulSoup(html_content, 'html.parser')
            tables = soup.find_all('table')
            mlst_table = None
            for table in tables:
                if table.find(string=re.compile(r'Sample|ST|Allele', re.I)):
                    mlst_table = table
                    break
            if not mlst_table:
                mlst_table = soup.find('table')
            if not mlst_table:
                return {}
            rows = mlst_table.find_all('tr')
            if len(rows) < 2:
                return {}
            headers = [cell.get_text().strip() for cell in rows[0].find_all(['th', 'td'])]
            data = []
            for row in rows[1:]:
                cols = row.find_all(['td', 'th'])
                if cols:
                    row_data = [col.get_text().strip() for col in cols]
                    if len(row_data) >= 2:
                        data.append(row_data)
            if not data:
                return {}
            df = pd.DataFrame(data)
            if len(df.columns) > len(headers):
                df = df.iloc[:, :len(headers)]
            df.columns = headers[:len(df.columns)]
            df.columns = [col.strip() for col in df.columns]
            if 'Sample' in df.columns:
                df['normalized_sample'] = df['Sample'].apply(self.normalize_sample_id)
            elif any('sample' in col.lower() for col in df.columns):
                sample_col = [col for col in df.columns if 'sample' in col.lower()][0]
                df['normalized_sample'] = df[sample_col].apply(self.normalize_sample_id)
            else:
                df['normalized_sample'] = df.iloc[:, 0].apply(self.normalize_sample_id)
            results = {}
            for _, row in df.iterrows():
                sample = row['normalized_sample']
                st = 'ND'
                if 'ST' in df.columns:
                    st_raw = str(row['ST']) if pd.notna(row['ST']) else 'ND'
                    st = self.clean_st(st_raw)
                elif 'st' in [col.lower() for col in df.columns]:
                    st_col = [col for col in df.columns if col.lower() == 'st'][0]
                    st_raw = str(row[st_col]) if pd.notna(row[st_col]) else 'ND'
                    st = self.clean_st(st_raw)
                allele_profile = 'ND'
                if 'Allele Profile' in df.columns:
                    allele_profile = str(row['Allele Profile']) if pd.notna(row['Allele Profile']) else 'ND'
                results[sample] = {'ST': st, 'Allele_Profile': allele_profile}
            print(f"    ✓ Found {len(results)} samples")
            return results
        except Exception as e:
            print(f"    ❌ Error parsing MLST: {e}")
            return {}
    
    def parse_past_report(self, file_path: Path) -> Dict[str, Dict]:
        print(f"  🧬 Parsing PAST serotype: {file_path.name}")
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                html_content = f.read()
            df = self.parse_html_table(html_content, 0)
            if df.empty:
                return {}
            df.columns = [col.strip() for col in df.columns]
            sample_col = None
            for col in df.columns:
                if 'sample' in col.lower() or 'id' in col.lower():
                    sample_col = col
                    break
            if not sample_col:
                sample_col = df.columns[0]
            df['normalized_sample'] = df[sample_col].apply(self.normalize_sample_id)
            results = {}
            for _, row in df.iterrows():
                sample = row['normalized_sample']
                o_type = 'ND'
                if 'Type' in df.columns:
                    o_type = str(row['Type']) if pd.notna(row['Type']) else 'ND'
                elif 'O-type' in df.columns:
                    o_type = str(row['O-type']) if pd.notna(row['O-type']) else 'ND'
                results[sample] = {'O_Type': o_type}
            print(f"    ✓ Found {len(results)} samples")
            return results
        except Exception as e:
            print(f"    ❌ Error parsing PAST: {e}")
            return {}
    
    def parse_amrfinder_report(self, file_path: Path) -> Tuple[Dict[str, List], Dict[str, Dict]]:
        print(f"  🧬 Parsing AMRfinder: {file_path.name}")
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                html_content = f.read()
            soup = BeautifulSoup(html_content, 'html.parser')
            tables = soup.find_all('table')
            if len(tables) < 2:
                return {}, {}
            gene_frequencies = {}
            df2 = self.parse_html_table(str(tables[1]), 0)
            if not df2.empty and 'Gene' in df2.columns:
                for _, row in df2.iterrows():
                    gene = str(row['Gene']).strip()
                    frequency = str(row.get('Frequency', '0')).strip()
                    genomes = []
                    if 'Genomes' in df2.columns and pd.notna(row.get('Genomes')):
                        genomes_str = str(row['Genomes'])
                        genomes = [self.normalize_sample_id(g.strip()) for g in genomes_str.split(',') if g.strip()]
                    count = 0
                    match = re.search(r'(\d+)', frequency)
                    if match:
                        count = int(match.group(1))
                    gene_frequencies[gene] = {
                        'frequency': frequency,
                        'count': count,
                        'genomes': genomes
                    }
            genes_by_genome = {}
            df1 = self.parse_html_table(str(tables[0]), 0)
            if not df1.empty:
                sample_col = None
                for col in df1.columns:
                    if 'genome' in col.lower() or 'sample' in col.lower():
                        sample_col = col
                        break
                if sample_col:
                    for _, row in df1.iterrows():
                        sample = self.normalize_sample_id(row[sample_col])
                        genes = []
                        genes_col = None
                        for col in df1.columns:
                            if 'genes' in col.lower() or 'detected' in col.lower():
                                genes_col = col
                                break
                        if genes_col and pd.notna(row.get(genes_col)):
                            gene_str = str(row[genes_col])
                            genes = [g.strip() for g in gene_str.split() if g.strip()]
                        genes_by_genome[sample] = genes
            print(f"    ✓ Found {len(genes_by_genome)} samples, {len(gene_frequencies)} genes")
            return genes_by_genome, gene_frequencies
        except Exception as e:
            print(f"    ❌ Error parsing AMRfinder: {e}")
            return {}, {}
    
    def parse_abricate_report(self, file_path: Path) -> Tuple[Dict[str, List], Dict[str, Dict]]:
        print(f"  🧬 Parsing ABRicate: {file_path.name}")
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                html_content = f.read()
            soup = BeautifulSoup(html_content, 'html.parser')
            tables = soup.find_all('table')
            if len(tables) < 2:
                return {}, {}
            db_name = 'unknown'
            for db in self.abricate_databases:
                if db in file_path.name.lower():
                    db_name = db
                    break
            gene_frequencies = {}
            df2 = self.parse_html_table(str(tables[1]), 0)
            if not df2.empty and 'Gene' in df2.columns:
                for _, row in df2.iterrows():
                    gene = str(row['Gene']).strip()
                    frequency = str(row.get('Frequency', '0')).strip()
                    genomes = []
                    if 'Genomes' in df2.columns and pd.notna(row.get('Genomes')):
                        genomes_str = str(row['Genomes'])
                        genomes = [self.normalize_sample_id(g.strip()) for g in genomes_str.split(',') if g.strip()]
                    count = 0
                    match = re.search(r'(\d+)', frequency)
                    if match:
                        count = int(match.group(1))
                    gene_frequencies[gene] = {
                        'frequency': frequency,
                        'count': count,
                        'genomes': genomes,
                        'database': db_name
                    }
            genes_by_genome = {}
            df1 = self.parse_html_table(str(tables[0]), 0)
            if not df1.empty:
                sample_col = None
                for col in df1.columns:
                    if 'genome' in col.lower() or 'sample' in col.lower():
                        sample_col = col
                        break
                if sample_col:
                    for _, row in df1.iterrows():
                        sample = self.normalize_sample_id(row[sample_col])
                        genes = []
                        genes_col = None
                        for col in df1.columns:
                            if 'genes' in col.lower() or 'detected' in col.lower():
                                genes_col = col
                                break
                        if genes_col and pd.notna(row.get(genes_col)):
                            gene_str = str(row[genes_col])
                            genes = [g.strip() for g in gene_str.split(',') if g.strip()]
                        genes_by_genome[sample] = genes
            print(f"    ✓ {db_name}: {len(genes_by_genome)} samples, {len(gene_frequencies)} genes")
            return genes_by_genome, gene_frequencies
        except Exception as e:
            print(f"    ❌ Error parsing ABRicate report: {e}")
            return {}, {}


# =============================================================================
# DATA ANALYZER CLASS
# =============================================================================
class PseudomonasDataAnalyzer:
    def __init__(self):
        self.critical_amr_genes = {
            'blaKPC', 'blaNDM', 'blaVIM', 'blaIMP', 'blaOXA', 'blaGES',
            'mcr-1', 'mcr-2', 'mcr-3', 'mcr-4', 'mcr-5', 'mcr-6',
            'armA', 'rmtA', 'rmtB', 'rmtC', 'rmtD'
        }
        self.critical_virulence_genes = {
            'exoU', 'exoS', 'exoT', 'exoY', 'exoA', 'toxA',
            'pld', 'plcH', 'plcN', 'lasB', 'lasA', 'aprA'
        }
    
    def create_gene_centric_tables(self, integrated_data: Dict[str, Any]) -> Dict[str, Any]:
        gene_centric = {
            'amr_databases': {},
            'virulence_databases': {},
            'combined_gene_frequencies': []
        }
        if 'amrfinder' in integrated_data.get('gene_frequencies', {}):
            amr_data = integrated_data['gene_frequencies']['amrfinder']
            gene_list = []
            for gene, data in amr_data.items():
                gene_list.append({
                    'gene': gene,
                    'database': 'AMRfinder',
                    'frequency': data.get('frequency', '0'),
                    'count': data.get('count', 0),
                    'genomes': data.get('genomes', [])
                })
            gene_centric['amr_databases']['amrfinder'] = sorted(gene_list, key=lambda x: x['count'], reverse=True)
        if 'abricate' in integrated_data.get('gene_frequencies', {}):
            for db_name, db_genes in integrated_data['gene_frequencies']['abricate'].items():
                gene_list = []
                for gene, data in db_genes.items():
                    gene_list.append({
                        'gene': gene,
                        'database': db_name.upper(),
                        'frequency': data.get('frequency', '0'),
                        'count': data.get('count', 0),
                        'genomes': data.get('genomes', [])
                    })
                if gene_list:
                    gene_list.sort(key=lambda x: x['count'], reverse=True)
                    if db_name in ['vfdb', 'ecoli_vf', 'pa_vf', 'pseudomonas_vf']:
                        gene_centric['virulence_databases'][db_name] = gene_list
                    else:
                        gene_centric['amr_databases'][db_name] = gene_list
        all_genes = []
        for db_type in ['amr_databases', 'virulence_databases']:
            for genes in gene_centric.get(db_type, {}).values():
                all_genes.extend(genes)
        all_genes.sort(key=lambda x: x['count'], reverse=True)
        gene_centric['combined_gene_frequencies'] = all_genes
        return gene_centric
    
    def create_cross_genome_patterns(self, integrated_data: Dict[str, Any]) -> Dict[str, Any]:
        patterns = {
            'st_distribution': Counter(),
            'o_type_distribution': Counter(),
            'st_o_combinations': defaultdict(list),
            'gene_cooccurrence': defaultdict(Counter)   # for top 100 co-occurrence
        }
        samples_data = integrated_data.get('samples', {})
        # Build sample->genes mapping for co-occurrence
        sample_genes = defaultdict(list)
        gene_centric = integrated_data.get('gene_centric', {})
        for db_type in ['amr_databases', 'virulence_databases']:
            for genes in gene_centric.get(db_type, {}).values():
                for gene_data in genes:
                    for genome in gene_data['genomes']:
                        if gene_data['gene'] not in sample_genes[genome]:
                            sample_genes[genome].append(gene_data['gene'])
        for sample, data in samples_data.items():
            st = data.get('mlst', {}).get('ST', 'ND')
            o_type = data.get('serotype', {}).get('O_Type', 'ND')
            if st != 'ND':
                patterns['st_distribution'][st] += 1
            if o_type != 'ND':
                patterns['o_type_distribution'][o_type] += 1
            if st != 'ND' and o_type != 'ND':
                patterns['st_o_combinations'][f"{st} - {o_type}"].append(sample)
            # Gene co-occurrence
            genes = sample_genes.get(sample, [])
            for i, g1 in enumerate(genes):
                for g2 in genes[i+1:]:
                    patterns['gene_cooccurrence'][g1][g2] += 1
        return patterns


# =============================================================================
# HTML GENERATOR CLASS
# =============================================================================
class PseudomonasHTMLGenerator:
    def __init__(self, data_analyzer: PseudomonasDataAnalyzer):
        self.data_analyzer = data_analyzer
    
    def generate_main_report(self, integrated_data: Dict[str, Any], output_dir: Path) -> str:
        print("\n🎨 Generating P. aeruginosa ULTIMATE HTML report...")
        html = self._create_ultimate_html(
            metadata=integrated_data.get('metadata', {}),
            samples_data=integrated_data.get('samples', {}),
            patterns=integrated_data.get('patterns', {}),
            gene_centric=integrated_data.get('gene_centric', {}),
            qc_data=integrated_data.get('qc_data', {}),
            integrated_data=integrated_data
        )
        output_file = output_dir / "genius_pseudomonas_ultimate_report.html"
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(html)
        print(f"    ✅ HTML report saved: {output_file}")
        return str(output_file)
    
    def _create_ultimate_html(self, **kwargs) -> str:
        css = """
        <style>
        :root {
            --brown: #8B4513;
            --brown-light: #A0522D;
            --brown-dark: #5C2E0B;
            --summary-color: var(--brown);
            --samples-color: #2E7D32;
            --qc-color: #00695C;
            --mlst-color: #1565C0;
            --serotype-color: #6A1B9A;
            --amr-color: #C62828;
            --virulence-color: #E65100;
            --patterns-color: #AD1457;
            --aiguide-color: #4527A0;
            --export-color: #37474F;
        }
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; background: #f5f5f5; min-width: 1200px; }
        .container { max-width: none; margin: 0 auto; padding: 20px; width: 100%; overflow-x: auto; }
        .main-header { background: linear-gradient(135deg, var(--brown-dark) 0%, var(--brown) 100%); color: white; padding: 30px; border-radius: 15px; margin-bottom: 30px; text-align: center; }
        .main-header h1 { font-size: 2.8em; margin-bottom: 10px; color: white; }
        .metadata-bar { background: rgba(255,255,255,0.1); padding: 15px; border-radius: 10px; margin: 20px 0; display: flex; justify-content: space-around; flex-wrap: wrap; gap: 15px; }
        .dashboard-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 20px; margin-bottom: 30px; }
        .dashboard-card { background: white; padding: 25px; border-radius: 12px; box-shadow: 0 5px 20px rgba(0,0,0,0.1); text-align: center; transition: all 0.3s ease; cursor: pointer; border-left: 5px solid; }
        .dashboard-card:hover { transform: translateY(-10px); }
        .card-number { font-size: 3em; font-weight: bold; margin: 15px 0; background: linear-gradient(90deg, var(--brown-dark), var(--brown)); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
        .tab-navigation { display: flex; gap: 5px; margin-bottom: 20px; flex-wrap: wrap; background: white; padding: 15px; border-radius: 12px; position: sticky; top: 10px; z-index: 100; }
        .tab-button { padding: 12px 25px; background: #f5f5f5; border: none; border-radius: 8px; cursor: pointer; font-weight: 600; color: #666; transition: all 0.3s ease; display: flex; align-items: center; gap: 8px; }
        .tab-button.active { color: white; }
        .tab-button.summary.active { background: var(--summary-color); }
        .tab-button.samples.active { background: var(--samples-color); }
        .tab-button.qc.active { background: var(--qc-color); }
        .tab-button.mlst.active { background: var(--mlst-color); }
        .tab-button.serotype.active { background: var(--serotype-color); }
        .tab-button.amr.active { background: var(--amr-color); }
        .tab-button.virulence.active { background: var(--virulence-color); }
        .tab-button.patterns.active { background: var(--patterns-color); }
        .tab-button.aiguide.active { background: var(--aiguide-color); }
        .tab-button.export.active { background: var(--export-color); }
        .tab-content { display: none; background: white; padding: 30px; border-radius: 15px; margin-bottom: 30px; width: 100%; overflow-x: auto; animation: fadeIn 0.5s ease; }
        .tab-content.active { display: block; }
        @keyframes fadeIn { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }
        .section-header { color: #2c3e50; margin-bottom: 25px; padding-bottom: 15px; border-bottom: 3px solid var(--brown); font-size: 1.8em; display: flex; justify-content: space-between; }
        .data-table { width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 0.95em; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        .data-table th { background: var(--brown-dark); color: white; padding: 15px; text-align: left; cursor: pointer; white-space: nowrap; }
        .data-table th:hover { background: var(--brown); }
        .data-table td { padding: 12px; border-bottom: 1px solid #e0e0e0; vertical-align: top; word-wrap: break-word; }
        .data-table tr:hover { background: #f8f9fa; }
        .sort-icon { margin-left: 5px; font-size: 0.8em; opacity: 0.6; }
        .search-box { width: 100%; padding: 12px; margin-bottom: 20px; border: 2px solid #e0e0e0; border-radius: 8px; font-size: 1em; }
        .action-buttons { display: flex; gap: 10px; margin: 20px 0; flex-wrap: wrap; clear: both; }
        .action-btn { padding: 10px 20px; border: none; border-radius: 8px; cursor: pointer; font-weight: 600; display: inline-flex; align-items: center; gap: 8px; transition: 0.3s; }
        .action-btn:hover { transform: translateY(-2px); }
        .btn-primary { background: var(--brown); color: white; }
        .btn-danger { background: #dc3545; color: white; }
        .btn-warning { background: #ffc107; color: black; }
        .btn-info { background: #17a2b8; color: white; }
        .btn-secondary { background: #6c757d; color: white; }
        .btn-light { background: #f8f9fa; color: #212529; border: 1px solid #dee2e6; }
        .badge { display: inline-block; padding: 5px 15px; border-radius: 20px; font-size: 0.85em; font-weight: 600; margin: 2px; }
        .badge-critical { background: #8B0000; color: white; }
        .alert-box { padding: 20px; border-radius: 10px; margin: 20px 0; display: flex; align-items: center; gap: 20px; border-left: 5px solid; }
        .alert-info { background: #d1ecf1; color: #0c5460; border-left-color: #17a2b8; }
        .alert-danger { background: #f8d7da; color: #721c24; border-left-color: #dc3545; }
        .genome-list { display: flex; flex-wrap: wrap; gap: 5px; max-height: none; overflow: visible; }
        .genome-tag { background: #e3f2fd; color: #1976d2; padding: 3px 10px; border-radius: 12px; font-size: 0.85em; border: 1px solid #bbdefb; white-space: nowrap; }
        .footer { text-align: center; padding: 30px; background: linear-gradient(135deg, var(--brown-dark), var(--brown)); color: white; border-radius: 15px; margin-top: 40px; }
        .footer a { color: #ffd700; text-decoration: none; }
        .footer a:hover { text-decoration: underline; }
        .scientific-note { background: #f9f9e0; padding: 15px; border-radius: 10px; margin-bottom: 20px; border-left: 5px solid var(--brown); font-size: 0.95em; }
        @media print { .tab-navigation, .dashboard-grid, .search-box, .action-buttons, .print-section-btn { display: none; } .tab-content.active { display: block; } }
        </style>
        """
        
        js = """
        <script>
        function switchTab(tabName) {
            document.querySelectorAll('.tab-content').forEach(t => t.classList.remove('active'));
            document.querySelectorAll('.tab-button').forEach(b => b.classList.remove('active'));
            document.getElementById(tabName + '-tab').classList.add('active');
            event.currentTarget.classList.add('active');
            window.location.hash = tabName;
        }
        function searchTable(tableId, searchId) {
            const filter = document.getElementById(searchId).value.toUpperCase();
            const rows = document.getElementById(tableId).getElementsByTagName('tr');
            for (let i = 1; i < rows.length; i++) {
                let found = false;
                for (let cell of rows[i].getElementsByTagName('td')) {
                    if (cell.textContent.toUpperCase().indexOf(filter) > -1) { found = true; break; }
                }
                rows[i].style.display = found ? '' : 'none';
            }
        }
        function sortTable(tableId, colIndex, type) {
            const table = document.getElementById(tableId);
            const tbody = table.tBodies[0];
            const rows = Array.from(tbody.rows);
            const isAscending = table.getAttribute('data-sort-dir') !== 'asc';
            rows.sort((a,b) => {
                let aVal = a.cells[colIndex].innerText.trim();
                let bVal = b.cells[colIndex].innerText.trim();
                if (type === 'number') {
                    aVal = parseFloat(aVal.replace(/,/g,'')) || 0;
                    bVal = parseFloat(bVal.replace(/,/g,'')) || 0;
                    return isAscending ? aVal - bVal : bVal - aVal;
                } else {
                    return isAscending ? aVal.localeCompare(bVal) : bVal.localeCompare(aVal);
                }
            });
            tbody.append(...rows);
            table.setAttribute('data-sort-dir', isAscending ? 'asc' : 'desc');
            const headers = table.querySelectorAll('th');
            headers.forEach((th,idx) => { let icon = th.querySelector('.sort-icon'); if(icon) icon.innerHTML = '⇅'; });
            const currentHeader = headers[colIndex];
            const icon = currentHeader.querySelector('.sort-icon');
            if(icon) icon.innerHTML = isAscending ? '↑' : '↓';
        }
        function exportTableToCSV(tableId, filename) {
            const rows = document.getElementById(tableId).querySelectorAll('tr');
            const csv = [];
            for (let row of rows) {
                const cols = row.querySelectorAll('td, th');
                const rowData = Array.from(cols).map(c => '"' + c.innerText.replace(/"/g, '""') + '"');
                csv.push(rowData.join(','));
            }
            const blob = new Blob([csv.join('\\n')], {type: 'text/csv'});
            const a = document.createElement('a');
            a.href = URL.createObjectURL(blob);
            a.download = filename;
            a.click();
            URL.revokeObjectURL(a.href);
        }
        function printSection(sectionId) {
            const content = document.getElementById(sectionId);
            const win = window.open('', '_blank');
            win.document.write('<html><head><title>Print</title><style>' + document.querySelector('style').textContent + '</style></head><body>');
            win.document.write(content.innerHTML);
            win.document.write('</body></html>');
            win.document.close();
            win.print();
        }
        document.addEventListener('DOMContentLoaded', function() {
            const hash = window.location.hash.substring(1);
            if(hash) {
                let btn = document.querySelector(`.tab-button.${hash}`);
                if(btn) btn.click();
            } else document.querySelector('.tab-button').click();
            document.querySelectorAll('.data-table').forEach(table => {
                const headers = table.querySelectorAll('th');
                headers.forEach((th, idx) => {
                    const type = th.getAttribute('data-sort') || 'string';
                    th.style.cursor = 'pointer';
                    th.addEventListener('click', () => sortTable(table.id, idx, type));
                    let icon = document.createElement('span');
                    icon.className = 'sort-icon';
                    icon.innerHTML = '⇅';
                    th.appendChild(icon);
                });
            });
        });
        </script>
        """
        
        metadata = kwargs['metadata']
        samples = kwargs['samples_data']
        patterns = kwargs['patterns']
        gene_centric = kwargs['gene_centric']
        qc_data = kwargs.get('qc_data', {})
        total_amr = sum(len(genes) for genes in gene_centric.get('amr_databases', {}).values())
        total_vir = sum(len(genes) for genes in gene_centric.get('virulence_databases', {}).values())
        
        html = f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>GENIUS P. aeruginosa Ultimate Report</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
{css}{js}</head>
<body><div class="container">
<div class="main-header"><h1><i class="fas fa-dna"></i> GENIUS P. aeruginosa Ultimate Analysis Report</h1>
<p>Gene-Centric Cross-Genome Analysis with Complete Genome Lists</p>
<div class="metadata-bar"><div class="metadata-item"><i class="fas fa-calendar"></i> {metadata.get('analysis_date','Unknown')}</div>
<div class="metadata-item"><i class="fas fa-database"></i> Samples: {len(samples)}</div>
<div class="metadata-item"><i class="fas fa-user-md"></i> GENIUS P. aeruginosa v1.0.0</div>
<div class="metadata-item"><i class="fas fa-university"></i> University of Ghana Medical School</div></div></div>
<div class="dashboard-grid">
    <div class="dashboard-card card-summary" onclick="switchTab('summary')"><div class="card-number">{len(samples)}</div><div class="card-label">Total Samples</div><i class="fas fa-vial fa-2x"></i></div>
    <div class="dashboard-card card-mlst" onclick="switchTab('mlst')"><div class="card-number">{len(patterns.get('st_distribution',{}))}</div><div class="card-label">Unique STs</div><i class="fas fa-code-branch fa-2x"></i></div>
    <div class="dashboard-card card-serotype" onclick="switchTab('serotype')"><div class="card-number">{len(patterns.get('o_type_distribution',{}))}</div><div class="card-label">O-types</div><i class="fas fa-tag fa-2x"></i></div>
    <div class="dashboard-card card-amr" onclick="switchTab('amr')"><div class="card-number">{total_amr}</div><div class="card-label">AMR Genes</div><i class="fas fa-biohazard fa-2x"></i></div>
    <div class="dashboard-card card-virulence" onclick="switchTab('virulence')"><div class="card-number">{total_vir}</div><div class="card-label">Virulence Genes</div><i class="fas fa-virus fa-2x"></i></div>
</div>
<div class="tab-navigation">
    <button class="tab-button summary active" onclick="switchTab('summary')"><i class="fas fa-chart-pie"></i> Summary</button>
    <button class="tab-button samples" onclick="switchTab('samples')"><i class="fas fa-list-alt"></i> Sample Overview</button>
    <button class="tab-button qc" onclick="switchTab('qc')"><i class="fas fa-chart-line"></i> FASTA QC</button>
    <button class="tab-button mlst" onclick="switchTab('mlst')"><i class="fas fa-code-branch"></i> MLST</button>
    <button class="tab-button serotype" onclick="switchTab('serotype')"><i class="fas fa-tag"></i> O‑Serotype</button>
    <button class="tab-button amr" onclick="switchTab('amr')"><i class="fas fa-biohazard"></i> AMR Genes</button>
    <button class="tab-button virulence" onclick="switchTab('virulence')"><i class="fas fa-virus"></i> Virulence</button>
    <button class="tab-button patterns" onclick="switchTab('patterns')"><i class="fas fa-project-diagram"></i> Patterns</button>
    <button class="tab-button aiguide" onclick="switchTab('aiguide')"><i class="fas fa-robot"></i> AI Guide</button>
    <button class="tab-button export" onclick="switchTab('export')"><i class="fas fa-download"></i> Export</button>
</div>
<div id="summary-tab" class="tab-content active">{self._summary_section(kwargs)}</div>
<div id="samples-tab" class="tab-content">{self._samples_section(kwargs)}</div>
<div id="qc-tab" class="tab-content">{self._qc_section(kwargs)}</div>
<div id="mlst-tab" class="tab-content">{self._mlst_section(kwargs)}</div>
<div id="serotype-tab" class="tab-content">{self._serotype_section(kwargs)}</div>
<div id="amr-tab" class="tab-content">{self._amr_section(kwargs)}</div>
<div id="virulence-tab" class="tab-content">{self._virulence_section(kwargs)}</div>
<div id="patterns-tab" class="tab-content">{self._patterns_section(kwargs)}</div>
<div id="aiguide-tab" class="tab-content">{self._aiguide_section(kwargs)}</div>
<div id="export-tab" class="tab-content">{self._export_section(kwargs)}</div>
<div class="footer">
    <h3>GENIUS P. aeruginosa Ultimate Reporter v1.0.0</h3>
    <p>University of Ghana Medical School | Department of Medical Biochemistry</p>
    <p>Author: Brown Beckley &lt;brownbeckley94@gmail.com&gt;</p>
    <p>GitHub: <a href="https://github.com/bbeckley-hub/pseudoscope" target="_blank">https://github.com/bbeckley-hub/pseudoscope</a></p>
    <p>Generated on {metadata.get('analysis_date','Unknown')}</p>
</div>
</div></body></html>"""
        return html
    
    # -------------------------------------------------------------------------
    # Section generators
    # -------------------------------------------------------------------------
    
    def _summary_section(self, kwargs):
        samples = kwargs['samples_data']
        patterns = kwargs['patterns']
        total = len(samples)
        st_unique = len(patterns.get('st_distribution', {}))
        o_unique = len(patterns.get('o_type_distribution', {}))
        amr_total = sum(len(genes) for genes in kwargs['gene_centric'].get('amr_databases', {}).values())
        vir_total = sum(len(genes) for genes in kwargs['gene_centric'].get('virulence_databases', {}).values())
        return f"""
        <div class="scientific-note"><i class="fas fa-flask"></i> <strong>Scientific Summary</strong><br>
        This report provides a gene‑centric view of antimicrobial resistance (AMR) and virulence genes across {total} <em>Pseudomonas aeruginosa</em> genomes.
        Each gene is shown with the complete list of genomes that carry it. The dashboard summarises key typing results.
        </div>
        <div class="alert-box alert-info"><i class="fas fa-info-circle fa-2x"></i><div><h3>Analysis Overview</h3><p>Gene-centric report for <strong>{total}</strong> P. aeruginosa genomes.</p></div></div>
        <div class="action-buttons"><button class="action-btn btn-primary" onclick="switchTab('amr')"><i class="fas fa-biohazard"></i> View AMR Genes</button>
        <button class="action-btn btn-success" onclick="switchTab('virulence')"><i class="fas fa-virus"></i> View Virulence</button>
        <button class="action-btn btn-danger" onclick="switchTab('patterns')"><i class="fas fa-project-diagram"></i> ST‑O Combinations</button></div>
        <h3>Key Statistics</h3><div class="scrollable-table"><table id="summary-stats" class="data-table"><thead><tr><th data-sort="string">Metric</th><th data-sort="string">Count</th><th>Details</th></tr></thead><tbody>
        <tr><td>Total Samples</td><td><strong>{total}</strong></td><td>Complete genomic analysis</td></tr>
        <tr><td>Unique STs</td><td><strong>{st_unique}</strong></td><td>MLST (Pasteur scheme)</td></tr>
        <tr><td>Unique O‑types</td><td><strong>{o_unique}</strong></td><td>PAST serotyping</td></tr>
        <tr><td>AMR Genes</td><td><strong>{amr_total}</strong></td><td>All databases (AMRfinder + ABRicate)</td></tr>
        <tr><td>Virulence Genes</td><td><strong>{vir_total}</strong></td><td>VFDB etc.</td></tr>
        </tbody></table></div>
        """
    
    def _samples_section(self, kwargs):
        samples = kwargs['samples_data']
        qc_data = kwargs.get('qc_data', {})
        html = """
        <div class="scientific-note"><i class="fas fa-database"></i> <strong>Population Structure Overview</strong><br>
        <em>Pseudomonas aeruginosa</em> is an opportunistic pathogen with high intrinsic and acquired resistance. Understanding its population structure helps track outbreaks and resistance dissemination.
        <ul>
            <li><strong>MLST (Sequence Type)</strong>: Multi‑locus sequence typing (Pasteur scheme) defines STs. Dominant clones like ST111, ST235, ST244 are often associated with multidrug resistance.</li>
            <li><strong>O‑Serotype</strong>: Lipopolysaccharide O‑antigen types (e.g., O1–O20). Certain serotypes correlate with clinical syndromes and biofilm formation.</li>
            <li><strong>N50</strong>: Assembly quality metric (the shortest contig length such that half the genome is in contigs of that size or larger).</li>
        </ul>
        </div>
        <input type="text" class="search-box" id="search-samples" onkeyup="searchTable('samples-table','search-samples')" placeholder="🔍 Search samples...">
        <div class="action-buttons"><button class="action-btn btn-primary" onclick="exportTableToCSV('samples-table','sample_overview.csv')"><i class="fas fa-download"></i> Export CSV</button></div>
        <div class="scrollable-table"><table id="samples-table" class="data-table"><thead><tr><th data-sort="string">Sample</th><th data-sort="string">ST</th><th data-sort="string">O‑Type</th><th data-sort="number">N50</th><th data-sort="number">Virulence Count</th></tr></thead><tbody>
        """
        for sample, data in samples.items():
            st = data.get('mlst',{}).get('ST','ND')
            o_type = data.get('serotype',{}).get('O_Type','ND')
            n50 = qc_data.get(sample, {}).get('N50', 'ND')
            if isinstance(n50, float):
                n50 = f"{n50:,.0f}"
            vir_cnt = len(data.get('virulence_genes',[]))
            html += f'<tr><td><strong>{sample}</strong></td><td>{st}</td><td>{o_type}</td><td>{n50}</td><td>{vir_cnt}</td></tr>'
        html += '</tbody></table></div>'
        return html
    
    def _qc_section(self, kwargs):
        qc_data = kwargs.get('qc_data', {})
        if not qc_data:
            return '<div class="alert-box alert-warning"><i class="fas fa-exclamation-circle"></i><div>No FASTA QC data found.</div></div>'
        metrics = set()
        for d in qc_data.values():
            metrics.update(d.keys())
        metrics = sorted(metrics)
        html = """
        <div class="scientific-note"><i class="fas fa-chart-line"></i> <strong>FASTA Quality Control</strong><br>
        Quality metrics for each genome assembly including GC content, AT content, N50, N50, N75, N90, total length, etc. High‑quality assemblies are critical for accurate gene detection.
        </div>
        <input type="text" class="search-box" id="search-qc" onkeyup="searchTable('qc-table','search-qc')" placeholder="🔍 Search sample...">
        <div class="scrollable-table"><table id="qc-table" class="data-table"><thead><tr><th data-sort="string">Sample</th>"""
        for m in metrics:
            html += f'<th data-sort="number">{m}</th>'
        html += '</tr></thead><tbody>'
        for sample, vals in sorted(qc_data.items()):
            html += f'<tr><td><strong>{sample}</strong></td>'
            for m in metrics:
                v = vals.get(m, 'ND')
                if isinstance(v, float):
                    v = f"{v:,.0f}" if v > 1000 else f"{v:.2f}"
                html += f'<td>{v}</td>'
            html += '</tr>'
        html += '</tbody></table></div>'
        return html
    
    def _mlst_section(self, kwargs):
        patterns = kwargs['patterns']
        st_dist = patterns.get('st_distribution', Counter())
        total = sum(st_dist.values())
        html = f"""
        <div class="scientific-note"><i class="fas fa-code-branch"></i> <strong>MLST (Pasteur scheme)</strong><br>
        Multi‑locus sequence typing uses internal fragments of seven housekeeping genes (<em>acsA, aroE, guaA, mutL, nuoD, ppsA, trpE</em>). 
        Each unique combination defines a Sequence Type (ST). Globally disseminated high‑risk clones include ST111, ST235, ST244, ST277, etc.
        </div>
        <input type="text" class="search-box" id="search-mlst" onkeyup="searchTable('mlst-table','search-mlst')" placeholder="🔍 Search ST...">
        <div class="scrollable-table"><table id="mlst-table" class="data-table"><thead><tr><th data-sort="string">ST</th><th data-sort="number">Count</th><th data-sort="number">Percentage</th><th data-sort="string">Associated O‑types</th></tr></thead><tbody>
        """
        for st, cnt in st_dist.most_common():
            pct = cnt/total*100
            o_types = set()
            for combo in patterns.get('st_o_combinations',{}):
                if f"{st} - " in combo:
                    o_types.add(combo.split(" - ")[1])
            o_str = ', '.join(o_types) if o_types else 'ND'
            html += f'<tr><td><strong>{st}</strong></td><td>{cnt}</td><td>{pct:.1f}%</td><td>{o_str}</td></tr>'
        html += '</tbody></table></div>'
        return html
    
    def _serotype_section(self, kwargs):
        patterns = kwargs['patterns']
        samples = kwargs['samples_data']
        o_dist = patterns.get('o_type_distribution', Counter())
        total = sum(o_dist.values())
        html = f"""
        <div class="scientific-note"><i class="fas fa-tag"></i> <strong>O‑Serotype (PAST)</strong><br>
        The O‑antigen is a major surface determinant and vaccine target. P. aeruginosa has 20 serotypes (O1–O20). 
        Certain serotypes are associated with chronic infections (e.g., O1, O2, O5, O6, O11) and high‑risk clones.
        </div>
        <input type="text" class="search-box" id="search-serotype" onkeyup="searchTable('serotype-table','search-serotype')" placeholder="🔍 Search O‑type...">
        <div class="scrollable-table"><table id="serotype-table" class="data-table"><thead><tr><th data-sort="string">O‑Type</th><th data-sort="number">Count</th><th data-sort="number">Percentage</th><th data-sort="string">Samples</th></tr></thead><tbody>
        """
        for o, cnt in o_dist.most_common():
            if o == 'ND': continue
            pct = cnt/total*100
            sample_list = ', '.join([s for s,d in samples.items() if d.get('serotype',{}).get('O_Type') == o])
            html += f'<tr><td><strong>{o}</strong></td><td>{cnt}</td><td>{pct:.1f}%</td><td>{sample_list}</td></tr>'
        html += '</tbody></table></div>'
        return html
    
    def _amr_section(self, kwargs):
        gene_centric = kwargs['gene_centric']
        amr_db = gene_centric.get('amr_databases', {})
        total_samples = len(kwargs['samples_data'])
        html = """
        <div class="scientific-note"><i class="fas fa-biohazard"></i> <strong>Antimicrobial Resistance Genes</strong><br>
        <em>Pseudomonas aeruginosa</em> exhibits both intrinsic resistance (e.g., efflux pumps, AmpC) and acquired resistance (carbapenemases, ESBLs, 16S rRNA methyltransferases). 
        Critical resistance genes include <strong>blaKPC, blaNDM, blaVIM, blaIMP, blaOXA‑48‑like, mcr</strong> (colistin), and <strong>armA/rmt</strong> (aminoglycosides). 
        Use filter buttons to focus on major classes.
        </div>
        <input type="text" class="search-box" id="search-amr" onkeyup="searchTable('amr-table','search-amr')" placeholder="🔍 Search AMR genes...">
        <div class="action-buttons">
        """
        filters = [
            ("Carbapenemases (KPC)", "KPC"), ("Carbapenemases (NDM)", "NDM"), ("Carbapenemases (VIM)", "VIM"),
            ("Carbapenemases (IMP)", "IMP"), ("OXA‑48‑like", "OXA-48"), ("Other OXA", "OXA-"),
            ("ESBL (GES)", "GES"), ("ESBL (PER)", "PER"), ("ESBL (VEB)", "VEB"),
            ("Colistin (mcr)", "mcr"), ("Aminoglycosides (aac)", "aac"), ("Aminoglycosides (aph)", "aph"),
            ("Aminoglycosides (ant)", "ant"), ("16S rRNA methylases (armA)", "armA"), ("16S rRNA methylases (rmt)", "rmt"),
            ("Fosfomycin (fosA)", "fosA"), ("Sulfonamide (sul)", "sul"), ("Trimethoprim (dfr)", "dfr"),
            ("Chloramphenicol (cat)", "cat"), ("Tetracycline (tet)", "tet"), ("Macrolides (erm)", "erm"),
            ("Efflux pumps (mex)", "mex"), ("Efflux pumps (oprM)", "oprM"), ("Quinolone resistance (gyrA)", "gyrA"),
            ("Quinolone resistance (parC)", "parC"), ("Chromosomal oprD mutations", "oprD")
        ]
        for label, pattern in filters:
            html += f'<button class="action-btn btn-warning" onclick="document.getElementById(\'search-amr\').value=\'{pattern}\'; searchTable(\'amr-table\',\'search-amr\')">{label}</button>'
        html += '<button class="action-btn btn-light" onclick="document.getElementById(\'search-amr\').value=\'\'; searchTable(\'amr-table\',\'search-amr\')"><i class="fas fa-sync"></i> Clear</button>'
        html += '</div><div class="scrollable-table"><table id="amr-table" class="data-table"><thead><tr><th data-sort="string">Gene</th><th data-sort="string">Database</th><th data-sort="number">Count</th><th data-sort="number">%</th><th data-sort="string">Genomes</th></tr></thead><tbody>'
        all_genes = []
        for db, genes in amr_db.items():
            all_genes.extend(genes)
        all_genes.sort(key=lambda x: x['count'], reverse=True)
        for g in all_genes:
            pct = f"{(g['count']/total_samples)*100:.1f}%" if total_samples else "0%"
            is_critical = any(crit.lower() in g['gene'].lower() for crit in self.data_analyzer.critical_amr_genes)
            gene_display = f"<strong>{g['gene']}</strong>" + (" ⚠️" if is_critical else "")
            genome_tags = ''.join(f'<span class="genome-tag">{gen}</span>' for gen in g['genomes'])
            html += f'<tr><td>{gene_display}</td><td>{g["database"]}</td><td>{g["count"]}</td><td>{pct}</td><td><div class="genome-list">{genome_tags}</div></td></tr>'
        html += '</tbody></table></div>'
        return html
    
    def _virulence_section(self, kwargs):
        gene_centric = kwargs['gene_centric']
        vir_db = gene_centric.get('virulence_databases', {})
        total_samples = len(kwargs['samples_data'])
        html = """
        <div class="scientific-note"><i class="fas fa-virus"></i> <strong>Virulence Factors</strong><br>
        <em>Pseudomonas aeruginosa</em> produces numerous virulence factors including the type III secretion system (T3SS) effectors <strong>ExoU, ExoS, ExoT, ExoY</strong>, 
        exotoxin A (ToxA), elastases (LasB, LasA), pyocyanin, alginate, and siderophores. The presence of <strong>exoU</strong> is associated with acute cytotoxicity and poor outcomes.
        </div>
        <input type="text" class="search-box" id="search-vir" onkeyup="searchTable('vir-table','search-vir')" placeholder="🔍 Search virulence genes...">
        <div class="action-buttons">
        """
        filters = [
            ("T3SS effectors (ExoU)", "exoU"), ("T3SS effectors (ExoS)", "exoS"), ("T3SS effectors (ExoT)", "exoT"), ("T3SS effectors (ExoY)", "exoY"),
            ("Exotoxin A (toxA)", "toxA"), ("Exotoxin A (exoA)", "exoA"), ("Phospholipase C (plcH)", "plcH"), ("Phospholipase C (plcN)", "plcN"),
            ("Elastase (lasB)", "lasB"), ("Elastase (lasA)", "lasA"), ("Protease (aprA)", "aprA"), ("Pyocyanin (phz)", "phz"),
            ("Alginate (alg)", "alg"), ("Pyoverdine (pvd)", "pvd"), ("Pyochelin (pch)", "pch"), ("Exopolysaccharide (psl)", "psl"),
            ("Type IV pili (pil)", "pil"), ("Flagella (fli)", "fli"), ("LecA (PA‑IL)", "lecA"), ("LecB (PA‑IIL)", "lecB"),
            ("T6SS (hcp)", "hcp"), ("T6SS (vgrG)", "vgrG"), ("Biofilm (pel)", "pel"), ("Cup fimbriae (cup)", "cup"),
            ("Hemolysin (phl)", "phl")
        ]
        for label, pattern in filters:
            html += f'<button class="action-btn btn-info" onclick="document.getElementById(\'search-vir\').value=\'{pattern}\'; searchTable(\'vir-table\',\'search-vir\')">{label}</button>'
        html += '<button class="action-btn btn-light" onclick="document.getElementById(\'search-vir\').value=\'\'; searchTable(\'vir-table\',\'search-vir\')">Clear</button>'
        html += '</div><div class="scrollable-table"><table id="vir-table" class="data-table"><thead><tr><th data-sort="string">Gene</th><th data-sort="string">Database</th><th data-sort="number">Count</th><th data-sort="number">%</th><th data-sort="string">Genomes</th></tr></thead><tbody>'
        all_genes = []
        for db, genes in vir_db.items():
            all_genes.extend(genes)
        all_genes.sort(key=lambda x: x['count'], reverse=True)
        for g in all_genes:
            pct = f"{(g['count']/total_samples)*100:.1f}%" if total_samples else "0%"
            is_critical = any(crit.lower() in g['gene'].lower() for crit in self.data_analyzer.critical_virulence_genes)
            gene_display = f"<strong>{g['gene']}</strong>" + (" ⚠️" if is_critical else "")
            genome_tags = ''.join(f'<span class="genome-tag">{gen}</span>' for gen in g['genomes'])
            html += f'<tr><td>{gene_display}</td><td>{g["database"]}</td><td>{g["count"]}</td><td>{pct}</td><td><div class="genome-list">{genome_tags}</div></td></tr>'
        html += '</tbody></table></div>'
        return html
    
    def _patterns_section(self, kwargs):
        patterns = kwargs['patterns']
        html = """
        <div class="scientific-note"><i class="fas fa-project-diagram"></i> <strong>Cross‑Genome Patterns</strong><br>
        This section shows the ST‑O combination table and the top 100 gene co‑occurrence pairs across all genomes.
        </div>
        <div class="alert-box alert-info"><i class="fas fa-table"></i><div><h3>ST‑O Combination Table</h3><p>Each combination of Sequence Type and O‑serotype with sample list.</p></div></div>
        <input type="text" class="search-box" id="search-sto" onkeyup="searchTable('sto-table','search-sto')" placeholder="🔍 Search ST-O combinations...">
        <div class="scrollable-table"><table id="sto-table" class="data-table"><thead><tr><th data-sort="string">ST - O</th><th data-sort="number">Count</th><th data-sort="string">Samples</th></tr></thead><tbody>
        """
        sto = patterns.get('st_o_combinations', {})
        for combo, samples in sorted(sto.items(), key=lambda x: len(x[1]), reverse=True):
            html += f'<tr><td><strong>{combo}</strong></td><td>{len(samples)}</td><td>{", ".join(samples)}</td></tr>'
        html += '</tbody></table></div>'
        
        # Gene co-occurrence top 100
        cooc = patterns.get('gene_cooccurrence', {})
        cooc_list = []
        for g1, partners in cooc.items():
            for g2, cnt in partners.items():
                cooc_list.append((g1, g2, cnt))
        cooc_list.sort(key=lambda x: x[2], reverse=True)
        if cooc_list:
            html += '<h3>Top 100 Gene Co‑occurrences</h3>'
            html += '<input type="text" class="search-box" id="search-cooc" onkeyup="searchTable(\'cooc-table\',\'search-cooc\')" placeholder="🔍 Search co‑occurrence pairs...">'
            html += '<div class="scrollable-table"><table id="cooc-table" class="data-table"><thead><tr><th data-sort="string">Gene 1</th><th data-sort="string">Gene 2</th><th data-sort="number">Co‑occurrence Count</th></tr></thead><tbody>'
            for g1, g2, cnt in cooc_list[:100]:
                html += f'<tr><td>{g1}</td><td>{g2}</td><td>{cnt}</td></tr>'
            html += '</tbody></table></div>'
        return html
    
    def _aiguide_section(self, kwargs):
        return """
        <div class="scientific-note"><i class="fas fa-robot"></i> <strong>AI Assistant Guide</strong><br>
        Upload this HTML or the JSON file to ChatGPT, Claude, or Gemini to ask questions about the data.
        </div>
        <div class="alert-box alert-info"><i class="fas fa-lightbulb"></i><div><h3>Example questions for P. aeruginosa:</h3>
        <ul>
        <li>Which STs carry carbapenemase genes (blaKPC, blaNDM, blaVIM)?</li>
        <li>List all samples with exoU (cytotoxic effector).</li>
        <li>What is the most common O‑serotype among ST111?</li>
        <li>Show me ST‑O combinations associated with high‑risk AMR profiles.</li>
        <li>Which resistance genes co‑occur most frequently with blaVIM‑2?</li>
        <li>Are there samples with both colistin resistance (mcr) and exoU?</li>
        </ul></div></div>
        """
    
    def _export_section(self, kwargs):
        return """
        <div class="alert-box alert-info"><i class="fas fa-download"></i><div>Export data tables as CSV or download complete JSON.</div></div>
        <div class="action-buttons">
            <button class="action-btn btn-primary" onclick="exportTableToCSV('samples-table','sample_overview.csv')">Sample Overview CSV</button>
            <button class="action-btn btn-primary" onclick="exportTableToCSV('amr-table','amr_genes.csv')">AMR Genes CSV</button>
            <button class="action-btn btn-primary" onclick="exportTableToCSV('vir-table','virulence_genes.csv')">Virulence Genes CSV</button>
            <button class="action-btn btn-primary" onclick="exportTableToCSV('qc-table','fasta_qc.csv')">FASTA QC CSV</button>
            <button class="action-btn btn-primary" onclick="exportTableToCSV('cooc-table','gene_cooccurrence.csv')">Co‑occurrence CSV</button>
            <button class="action-btn btn-success" onclick="location.href='genius_pseudomonas_ultimate_report.json'">Download JSON</button>
        </div>
        """


# =============================================================================
# MASTER REPORTER CLASS
# =============================================================================
class GeniusPseudomonasUltimateReporter:
    def __init__(self, input_dir: Path):
        self.input_dir = Path(input_dir)
        self.output_dir = self.input_dir / "GENIUS_PSEUDOMONAS_ULTIMATE_REPORTS"
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.parser = PseudomonasHTMLParser()
        self.analyzer = PseudomonasDataAnalyzer()
        self.html_generator = PseudomonasHTMLGenerator(self.analyzer)
        self.metadata = {
            "tool_name": "GENIUS P. aeruginosa Ultimate Reporter",
            "version": "1.0.0",
            "author": "Brown Beckley <brownbeckley94@gmail.com>",
            "affiliation": "University of Ghana Medical School",
            "analysis_date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "input_directory": str(self.input_dir)
        }
    
    def find_html_files(self) -> Dict[str, List[Path]]:
        print("🔍 Searching for HTML reports...")
        html_files = {
            'mlst': [], 'past': [], 'amrfinder': [], 'abricate': [], 'qc': []
        }
        for html_file in self.input_dir.glob("**/*.html"):
            name = html_file.name.lower()
            if 'mlst' in name:
                html_files['mlst'].append(html_file)
            elif 'past' in name or 'serotype' in name:
                html_files['past'].append(html_file)
            elif 'amrfinder' in name or 'resistance' in name:
                html_files['amrfinder'].append(html_file)
            elif 'fasta_qc' in name or 'qc_summary' in name:
                html_files['qc'].append(html_file)
            elif 'abricate' in name or any(db in name for db in self.parser.abricate_databases):
                html_files['abricate'].append(html_file)
        for k, v in html_files.items():
            if v:
                print(f"  📁 {k.upper()}: {len(v)} files found")
        return html_files
    
    def integrate_all_data(self, html_files: Dict[str, List[Path]]) -> Dict[str, Any]:
        print("\n🔗 Integrating data...")
        integrated = {
            'metadata': self.metadata,
            'samples': {},
            'patterns': {},
            'gene_centric': {},
            'qc_data': {}
        }
        
        if html_files['qc']:
            integrated['qc_data'] = self.parser.parse_qc_report(html_files['qc'][0])
        
        mlst_data = {}
        if html_files['mlst']:
            mlst_data = self.parser.parse_mlst_report(html_files['mlst'][0])
        
        past_data = {}
        if html_files['past']:
            past_data = self.parser.parse_past_report(html_files['past'][0])
        
        amr_by_sample, amr_gene_freq = {}, {}
        if html_files['amrfinder']:
            amr_by_sample, amr_gene_freq = self.parser.parse_amrfinder_report(html_files['amrfinder'][0])
        
        abricate_by_sample = defaultdict(dict)
        abricate_gene_freq = {}
        for f in html_files['abricate']:
            genes_by_sample, gene_freq = self.parser.parse_abricate_report(f)
            db_name = 'unknown'
            for db in self.parser.abricate_databases:
                if db in f.name.lower():
                    db_name = db
                    break
            for samp, gs in genes_by_sample.items():
                abricate_by_sample[samp][db_name] = gs
            abricate_gene_freq[db_name] = gene_freq
        
        all_samples = set()
        all_samples.update(mlst_data.keys())
        all_samples.update(past_data.keys())
        all_samples.update(amr_by_sample.keys())
        all_samples.update(abricate_by_sample.keys())
        all_samples.update(integrated['qc_data'].keys())
        
        if not all_samples:
            print("❌ No samples found in any report!")
            return {}
        
        print(f"📊 Found {len(all_samples)} unique samples")
        
        for sample in all_samples:
            virulence_genes = []
            for db in ['vfdb', 'ecoli_vf', 'pa_vf', 'pseudomonas_vf']:
                if db in abricate_by_sample.get(sample, {}):
                    virulence_genes.extend(abricate_by_sample[sample][db])
            
            integrated['samples'][sample] = {
                'mlst': mlst_data.get(sample, {'ST': 'ND', 'Allele_Profile': 'ND'}),
                'serotype': past_data.get(sample, {'O_Type': 'ND'}),
                'amr_genes': amr_by_sample.get(sample, []),
                'virulence_genes': list(set(virulence_genes))
            }
        
        integrated['gene_frequencies'] = {
            'amrfinder': amr_gene_freq,
            'abricate': abricate_gene_freq
        }
        
        print("\n🧠 Processing gene-centric analysis...")
        integrated['gene_centric'] = self.analyzer.create_gene_centric_tables(integrated)
        integrated['patterns'] = self.analyzer.create_cross_genome_patterns(integrated)
        
        return integrated
    
    def generate_json_report(self, data: Dict[str, Any]) -> Path:
        print("\n📝 Generating JSON report...")
        out = self.output_dir / "genius_pseudomonas_ultimate_report.json"
        with open(out, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, default=str)
        print(f"    ✅ JSON saved: {out}")
        return out
    
    def generate_csv_reports(self, data: Dict[str, Any]):
        print("\n📊 Generating CSV reports...")
        samples_df = pd.DataFrame([{
            'Sample': s,
            'ST': d['mlst']['ST'],
            'O_Type': d['serotype']['O_Type'],
            'Virulence_Count': len(d['virulence_genes'])
        } for s, d in data['samples'].items()])
        samples_df.to_csv(self.output_dir / "sample_overview.csv", index=False)
        
        amr_rows = []
        for db, genes in data['gene_centric'].get('amr_databases', {}).items():
            for g in genes:
                amr_rows.append({
                    'Gene': g['gene'],
                    'Database': g['database'],
                    'Count': g['count'],
                    'Genomes': ';'.join(g['genomes'])
                })
        if amr_rows:
            pd.DataFrame(amr_rows).to_csv(self.output_dir / "amr_genes.csv", index=False)
        
        vir_rows = []
        for db, genes in data['gene_centric'].get('virulence_databases', {}).items():
            for g in genes:
                vir_rows.append({
                    'Gene': g['gene'],
                    'Database': g['database'],
                    'Count': g['count'],
                    'Genomes': ';'.join(g['genomes'])
                })
        if vir_rows:
            pd.DataFrame(vir_rows).to_csv(self.output_dir / "virulence_genes.csv", index=False)
        
        # Co-occurrence CSV
        cooc = data['patterns'].get('gene_cooccurrence', {})
        cooc_list = []
        for g1, partners in cooc.items():
            for g2, cnt in partners.items():
                cooc_list.append((g1, g2, cnt))
        cooc_list.sort(key=lambda x: x[2], reverse=True)
        if cooc_list:
            pd.DataFrame(cooc_list[:100], columns=['Gene1', 'Gene2', 'Count']).to_csv(self.output_dir / "gene_cooccurrence.csv", index=False)
        
        print("    ✅ CSV reports generated.")
    
    def run(self):
        print("=" * 80)
        print("🧠 GENIUS P. AERUGINOSA ULTIMATE REPORTER v1.0.0")
        print("=" * 80)
        print(f"📁 Input directory: {self.input_dir}")
        
        html_files = self.find_html_files()
        if not any(html_files.values()):
            print("❌ No HTML report files found!")
            return False
        
        data = self.integrate_all_data(html_files)
        if not data:
            return False
        
        print("\n" + "=" * 80)
        print("📊 GENERATING ULTIMATE REPORTS")
        print("=" * 80)
        self.generate_json_report(data)
        self.generate_csv_reports(data)
        self.html_generator.generate_main_report(data, self.output_dir)
        
        total_samples = len(data['samples'])
        patterns = data['patterns']
        gene_centric = data['gene_centric']
        total_amr = sum(len(genes) for genes in gene_centric.get('amr_databases', {}).values())
        total_vir = sum(len(genes) for genes in gene_centric.get('virulence_databases', {}).values())
        
        print("\n" + "=" * 80)
        print("✅ ULTIMATE ANALYSIS COMPLETE!")
        print("=" * 80)
        print(f"📁 Output directory: {self.output_dir}")
        print(f"📄 Files generated:")
        print(f"   • genius_pseudomonas_ultimate_report.html (Interactive report)")
        print(f"   • genius_pseudomonas_ultimate_report.json (Complete data)")
        print(f"   • sample_overview.csv")
        print(f"   • amr_genes.csv")
        print(f"   • virulence_genes.csv")
        print(f"   • gene_cooccurrence.csv")
        print(f"\n📈 ANALYSIS SUMMARY:")
        print(f"   • {total_samples} total samples analyzed")
        print(f"   • {total_amr} AMR genes")
        print(f"   • {total_vir} virulence genes")
        print("\n🎯 Next steps:")
        print("   1. Open genius_pseudomonas_ultimate_report.html in your browser")
        print("   2. Explore AMR and Virulence tabs to see genes with ALL genomes")
        print("   3. Use filter buttons to focus on key resistance/virulence genes")
        print("   4. Examine ST-O combination table and gene co-occurrence under Patterns tab")
        print("   5. Export data using the Export tab or individual CSV buttons")
        print("\n" + "=" * 80)
        return True


# =============================================================================
# MAIN ENTRY POINT
# =============================================================================
def main():
    parser = argparse.ArgumentParser(
        description='GENIUS P. aeruginosa Ultimate Reporter - Gene-Centric Analysis',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python p_ultimate.py -i /path/to/html/reports

Author: Brown Beckley <brownbeckley94@gmail.com>
Affiliation: University of Ghana Medical School, Department of Medical Biochemistry
        """
    )
    parser.add_argument('-i', '--input-dir', required=True,
                        help='Directory containing HTML report files')
    parser.add_argument('-o', '--output-dir',
                        help='Custom output directory (default: input_dir/GENIUS_PSEUDOMONAS_ULTIMATE_REPORTS)')
    
    args = parser.parse_args()
    input_dir = Path(args.input_dir)
    
    if not input_dir.exists():
        print(f"❌ Input directory not found: {input_dir}")
        sys.exit(1)
    
    reporter = GeniusPseudomonasUltimateReporter(input_dir)
    
    if args.output_dir:
        reporter.output_dir = Path(args.output_dir)
        reporter.output_dir.mkdir(parents=True, exist_ok=True)
    
    success = reporter.run()
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()